sudo: false

language: php

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - tests/_data

before_script:
  - composer update --dev --no-interaction

script:
  - echo "$DEBUG_CREDENTIALS_1"
  - echo "$DEBUG_CREDENTIALS_2"
  - echo "$DEBUG_CREDENTIALS_3"
  - echo "$SECRET"