sudo: false

language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'

cache:
  directories:
    - vendor
    - tests/_data

before_script:
  - composer update --dev --no-interaction

script:
  - vendor/bin/phpstan analyse
  - vendor/bin/phpunit